# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warning_are_errors: true

r_packages: stringi

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel

matrix:
  exclude:
    - os: osx
      r: devel

after_success:
    - Rscript -e 'covr::codecov(type = "all")'
